### ISSUE TITLE
Logo and search bar in header

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-advocates#1]
# Story

As a user, in order to find attractions I'm interested in, I need to type some value in a text box in the navigation bar at the top of the page, press enter, and see results

# Acceptance Criteria

**Given** a user visits the application
**When** the application renders
**Then** the application logo should appear on the left in a navigation bar

**Given** a user visits the application
**When** the application renders
**Then** a text field should appear in the middle of the navigation bar

**Given** the user types some characters into the search field
**When** user user presses enter
**Then** the areas that contain an attraction, whose name contains the search string, should be outlined with a border

# Technical Information

1. Use regular expressions to match the user's search string with the name of each attraction to find a match. The search string simply must be contained in the attraction name, not just start with.

**Comment by hagansmith** [comment]
![screen shot 2017-10-28 at 12 22 03 pm](https://user-images.githubusercontent.com/19448241/32136820-aa49c22e-bbda-11e7-8ef9-3e8376b33dd9.png)
[moqups](https://app.moqups.com/unsaved/f043389a/edit/page/afa73dfd5)

**Comment by jessibcoden** [comment]
[Use Bootstrap Navbar](https://getbootstrap.com/docs/3.3/components/#navbar)

**Comment by hagansmith** [comment]
👍
