### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-advocates#12]
# Story

As a developer, in order to DO ALL THE THINGS, I need the project to be setup

# Acceptance Criteria

**When** the developer clones the repo
**Then** they should have all the files they need

**Comment by hagansmith** [comment]
**Directory Structure**
dist/
javascripts/
  -- _main.js_
  -- _events.js
  -- firebaseApi.js
  -- api.js
  -- dom.js_
lib/
  -- [Gruntfile.js](https://gist.github.com/morecallan/732a2923b18c99c14ffd8d9838bf3410)
styles/
sass/
  --  _main.scss_
[.gitignore](https://gist.github.com/morecallan/732a2923b18c99c14ffd8d9838bf3410#what-goes-in-gitignore-when-working-in-teams-1)
_index.html_
_README.md_

**Comment by hagansmith** [comment]
[Install Dependencies](https://gist.github.com/morecallan/732a2923b18c99c14ffd8d9838bf3410#install-dependencies)
cd lib
npm init
npm install grunt grunt-contrib-jshint matchdep grunt-sass grunt-contrib-copy grunt-contrib-clean grunt-contrib-watch grunt-browserify jshint-stylish --save-dev
npm install jquery bootstrap --save
- Firebase -

**Comment by jessibcoden** [comment]
[Install MomentJs](http://momentjs.com/docs/#/use-it/node-js/)

npm install moment

Add "moment" to jshint predef in Gruntfile.js.

**Comment by jessibcoden** [comment]
Include Script Tags:
```
<script src="https://www.gstatic.com/firebasejs/4.6.0/firebase.js"></script>
<script type="text/javascript" src="./lib/node_modules/jquery/dist/jquery.js"></script>
<script type="text/javascript" src="./lib/node_modules/bootstrap/dist/js/bootstrap.js"></script>
<script type="text/javascript" src="./lib/node_modules/moment/min/moment.min.js"></script>
<script type="text/javascript" src="./dist/app.js"></script>
```

**Comment by jessibcoden** [comment]
Include Linke Tags:

```
	<link rel="stylesheet" type="text/css" href="lib/node_modules/bootstrap/dist/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="./styles/main.css">
```

**Comment by hagansmith** [comment]
Firebase with returned data
