### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-advocates#14]
# Story
As a developer, when I look at your readme,  I would like it to be real nice looking and very useful.

# Acceptance Criteria

**When** anyone looks at your readme
**Then** they should know everything they need to know about your project.

**Comment by hagansmith** [comment]
![img_3487](https://user-images.githubusercontent.com/19448241/32300677-b18f152e-bf28-11e7-80f3-e3aeb2889909.jpg)
![img_3488](https://user-images.githubusercontent.com/19448241/32300679-b1b49236-bf28-11e7-8b64-cba25bf07661.jpg)
![img_3485 2](https://user-images.githubusercontent.com/19448241/32300680-b1c1e224-bf28-11e7-8fc7-99e6c3b22ce7.jpg)
